name: neural_array
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2022.9.24
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - libffi=3.3
  - openssl=1.1.1s
  - pip=22.2.2
  - python=3.8.13
  - setuptools=65.5.0
  - sqlite=3.39.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - absl-py==0.15.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - astunparse==1.6.3
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cachetools==5.2.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - clang==5.0
    - cloudpickle==2.2.0
    - contourpy==1.0.6
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dm-tree==0.1.7
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - flatbuffers==1.12
    - fonttools==4.38.0
    - gast==0.4.0
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.50.0
    - h5py==3.1.0
    - idna==3.4
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - ipykernel==6.17.1
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonschema==4.17.0
    - jupyter==1.0.0
    - jupyter-client==7.4.5
    - jupyter-console==6.4.4
    - jupyter-core==5.0.0
    - jupyter-server==1.23.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.4
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.19.5
    - oauthlib==3.2.2
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.4
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.32
    - protobuf==3.19.6
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pyzmq==24.0.1
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.9.3
    - send2trash==1.8.0
    - six==1.15.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-addons==0.16.1
    - tensorflow-estimator==2.7.0
    - tensorflow-gpu==2.7.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - tensorflow-probability==0.15.0
    - termcolor==1.1.0
    - terminado==0.17.0
    - tinycss2==1.2.1
    - tornado==6.2
    - traitlets==5.5.0
    - typeguard==2.13.3
    - typing-extensions==3.7.4.3
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - wrapt==1.12.1
    - zipp==3.10.0
    - imageio==2.32.0
    - mat73==0.60
